package dev.visuals.blueprint.motion

import dev.visuals.blueprint.model.AnimatedProperty
import dev.visuals.blueprint.model.EasingSpec
import dev.visuals.blueprint.model.MotionElement
import dev.visuals.blueprint.model.MotionSpec
import dev.visuals.blueprint.model.PropertyAnimation
import java.math.BigDecimal
import java.math.RoundingMode
import kotlin.math.abs
import kotlin.math.roundToLong

/**
 * Writes one `@Composable <Element>Motion(play, modifier, content)` per element that replays the
 * measured motion on any content through `graphicsLayer`. Distances are converted with [pxPerDp];
 * delays count from the first motion in the video.
 */
object ComposeWriter {

    private data class Channel(val local: String, val assignments: List<String>, val toDp: Boolean)

    private val CHANNELS = mapOf(
        AnimatedProperty.TRANSLATION_X to Channel("offsetX", listOf("translationX = offsetX.value.dp.toPx()"), toDp = true),
        AnimatedProperty.TRANSLATION_Y to Channel("offsetY", listOf("translationY = offsetY.value.dp.toPx()"), toDp = true),
        AnimatedProperty.SCALE to Channel("scale", listOf("scaleX = scale.value", "scaleY = scale.value"), toDp = false),
        AnimatedProperty.ROTATION to Channel("rotation", listOf("rotationZ = rotation.value"), toDp = false),
        AnimatedProperty.ALPHA to Channel("opacity", listOf("alpha = opacity.value"), toDp = false),
    )

    fun write(spec: MotionSpec, packageName: String, pxPerDp: Double): String {
        require(pxPerDp > 0) { "pxPerDp must be positive" }
        val animations = spec.elements.flatMap { it.animations }
        val origin = animations.minOfOrNull { it.startMs } ?: 0.0
        val body = spec.elements.joinToString("\n") { element(it, origin, pxPerDp) }
        return buildString {
            appendLine("// Generated by `blueprint motion` from ${spec.source.file}. Do not edit by hand.")
            appendLine("// Distances: video px / ${number(pxPerDp)} px per dp. Delays count from the first motion (${number(origin)} ms into the video).")
            appendLine("package $packageName")
            appendLine()
            imports(spec.elements).forEach { appendLine("import $it") }
            appendLine()
            append(body)
        }
    }

    private fun imports(elements: List<MotionElement>): List<String> = buildList {
        val animations = elements.flatMap { it.animations }
        add("androidx.compose.animation.core.Animatable")
        if (animations.any { it.easing is EasingSpec.CubicBezier }) {
            add("androidx.compose.animation.core.CubicBezierEasing")
            add("androidx.compose.animation.core.tween")
        }
        if (animations.any { it.easing is EasingSpec.Spring }) add("androidx.compose.animation.core.spring")
        add("androidx.compose.foundation.layout.Box")
        add("androidx.compose.runtime.Composable")
        add("androidx.compose.runtime.LaunchedEffect")
        add("androidx.compose.runtime.remember")
        add("androidx.compose.ui.Modifier")
        add("androidx.compose.ui.graphics.graphicsLayer")
        if (elements.any { transformOrigin(it) != null }) add("androidx.compose.ui.graphics.TransformOrigin")
        if (animations.any { CHANNELS.getValue(it.property).toDp }) add("androidx.compose.ui.unit.dp")
        add("kotlinx.coroutines.delay")
        add("kotlinx.coroutines.launch")
    }.sorted()

    private fun element(element: MotionElement, origin: Double, pxPerDp: Double): String = buildString {
        val channels = element.animations.map { it to CHANNELS.getValue(it.property) }
        fun value(animation: PropertyAnimation, v: Double) =
            if (CHANNELS.getValue(animation.property).toDp) v / pxPerDp else v
        val b = element.bounds
        appendLine("/**")
        appendLine(" * ${element.id}: ${number(b.width)}×${number(b.height)} px at (${number(b.x)}, ${number(b.y)}), ${element.color}, tracked by ${element.tracking.name.lowercase()}.")
        appendLine(" * Plays the measured motion on [content] when [play] becomes true and resets when it becomes false.")
        appendLine(" */")
        appendLine("@Composable")
        appendLine("fun ${element.id.replaceFirstChar(Char::uppercaseChar)}Motion(play: Boolean, modifier: Modifier = Modifier, content: @Composable () -> Unit) {")
        channels.forEach { (animation, channel) ->
            appendLine("    val ${channel.local} = remember { Animatable(${float(value(animation, animation.from))}) }")
        }
        appendLine("    LaunchedEffect(play) {")
        appendLine("        if (!play) {")
        channels.forEach { (animation, channel) -> appendLine("            ${channel.local}.snapTo(${float(value(animation, animation.from))})") }
        appendLine("            return@LaunchedEffect")
        appendLine("        }")
        channels.forEach { (animation, channel) ->
            appendLine("        launch {")
            val delayMs = (animation.startMs - origin).roundToLong()
            if (delayMs > 0) appendLine("            delay(${delayMs}L)")
            appendLine("            ${channel.local}.animateTo(${float(value(animation, animation.to))}, ${spec(animation)})")
            appendLine("        }")
        }
        appendLine("    }")
        appendLine("    Box(")
        appendLine("        modifier.graphicsLayer {")
        transformOrigin(element)?.let { appendLine("            transformOrigin = $it") }
        channels.flatMap { it.second.assignments }.forEach { appendLine("            $it") }
        appendLine("        },")
        appendLine("    ) {")
        appendLine("        content()")
        appendLine("    }")
        appendLine("}")
    }

    /** `TransformOrigin(x, y)` for an off-centre pivot of a scale/rotation, as fractions of the bounds. */
    private fun transformOrigin(element: MotionElement): String? {
        val turns = element.animations.any { it.property == AnimatedProperty.SCALE || it.property == AnimatedProperty.ROTATION }
        val b = element.bounds
        if (!turns || b.width <= 0 || b.height <= 0) return null
        val x = (element.pivot.x - b.x) / b.width
        val y = (element.pivot.y - b.y) / b.height
        if (abs(x - 0.5) < CENTRE_TOLERANCE && abs(y - 0.5) < CENTRE_TOLERANCE) return null
        return "TransformOrigin(${float(x)}, ${float(y)})"
    }

    private fun spec(animation: PropertyAnimation): String = when (val easing = animation.easing) {
        is EasingSpec.CubicBezier ->
            "tween(durationMillis = ${animation.durationMs.roundToLong()}, easing = CubicBezierEasing(" +
                "${float(easing.x1)}, ${float(easing.y1)}, ${float(easing.x2)}, ${float(easing.y2)}))"
        is EasingSpec.Spring ->
            "spring(dampingRatio = ${float(easing.dampingRatio)}, stiffness = ${float(easing.stiffness)})"
    }

    private fun number(value: Double): String =
        BigDecimal(value).setScale(3, RoundingMode.HALF_UP).stripTrailingZeros().toPlainString()

    private fun float(value: Double): String = number(value) + "f"

    private const val CENTRE_TOLERANCE = 0.01
}
